- name: Configure DB server
  hosts: localhost
  become: yes
  tasks:
  - name: Remove broken MySQL repo files
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    loop:
      - /etc/yum.repos.d/mysql-community.repo
      - /etc/yum.repos.d/mysql-community-source.repo

  - name: Create explicit MySQL 8.0 repo file
    ansible.builtin.copy:
      dest: /etc/yum.repos.d/mysql.repo
      content: |
        [mysql80-community]
        name=MySQL 8.0 Community Server
        baseurl=https://mysql.com
        enabled=1
        gpgcheck=1
        gpgkey=https://mysql.com

  - name: Clean DNF cache and install MySQL Server
    ansible.builtin.dnf:
      name: mysql-community-server
      state: present
      update_cache: yes
  - name: print info
    ansible.builtin.debug:
       msg: "{{ERROR}}"
  - name: Start and Enable MySQL Service
    ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes 
    ignore_errors: true

