- name: Configure DB server
  hosts: localhost
  become: yes
  tasks:
  # - name: Download MySQL Community Repository RPM
  #   ansible.builtin.get_url:
  #     url: https://mysql.com
  #     # url: https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm
  #     dest: /tmp/mysql80-community-release-el9-1.noarch.rpm
  #     http_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"

  # - name: Install Mysql Community Repository RPM
  #   ansible.builtin.dnf:
  #     name: /tmp/mysql80-community-release-el9-1.noarch.rpm
  #     state: present

  # - name: Import MySQL GPG Key
  #   ansible.builtin.rpm_key:
  #     state: present
  #     key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2023

  # - name: Install MySQL Server Package
  #   ansible.builtin.dnf:  
  #     name: mysql-community-server
  #     state: present
  #   ignore_errors: true
  #   register: ERROR

  # - name: print info
  #   ansible.builtin.debug:
  #     msg: "{{ERROR}}"
  # - name: Start and Enable MySQL Service
  #   ansible.builtin.service:
  #     name: mysqld
  #     state: started
  #     enabled: yes 
  #   ignore_errors: true
    - name: Import MySQL 2023 GPG Key
      ansible.builtin.rpm_key:
        state: present
        key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2023

    - name: Install MySQL Community Repository via URL
      ansible.builtin.dnf:
        name: https://dev.mysql.com/get/mysql84-community-release-el9-1.noarch.rpm
        state: present
        disable_gpg_check: no

    - name: Disable MySQL 8.4 LTS (If you want to pin to MySQL 8.0)
      ansible.builtin.command: dnf config-manager --disable mysql-8.4-lts-community
      changed_when: false

    - name: Enable MySQL 8.0 Community Repository
      ansible.builtin.command: dnf config-manager --enable mysql80-community
      changed_when: false

    - name: Install MySQL Server Package
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present
        update_cache: yes

    - name: Start and Enable MySQL Service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes