- name: configure the DB server
  hosts: db
  vars:
    login_host: 172.31.45.57
  vars_prompt:
  - name: mysql_root_password
    prompt: please enter Mysql root login_password
    private: no

  tasks:
  - name: install mysql-community
    ansible.builtin.command: sudo dnf install -y https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm
  
  - name: import rpm
    ansible.builtin.command: sudo rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023

  - name: install mysql-community
    ansible.builtin.command: sudo dnf install -y mysql-community-server

  - name: Run & enable mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
    become: yes

  - name: Ensure python3-pip is installed
    ansible.builtin.dnf:
      name: python3-pip
      state: present
    become: yes
  - name: install python mysql dependencies
    ansible.builtin.pip:
      name: 
      - PyMySQL
      - cryptography
      executable: pip3.9

  - name: check DB connection
    community.mysql.mysql_info:
      login_user: "root"
      login_password: "{{mysql_root_password}}"
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: true
    register: mysql_connection_timeout

  - name: print output
    ansible.builtin.debug:
      msg: "output {{mysql_connection_timeout}}"

  - name: capture root_password_before changing
    ansible.builtin.command: sudo grep 'temporary password' /var/log/mysqld.log
    register: temp_password
    changed_when: false

  - name: Set password variable safely
    ansible.builtin.set_fact:
        # We target the stdout directly and extract everything after the final space
      actual_password: "{{ (temp_password.stdout | regex_findall(r'root@localhost:\s*(\S+)')) | last | default('NOT_FOUND') }}"

  - name: print temp_password
    ansible.builtin.debug:
      msg: -|
        "Temp_password is ::{{actual_password}}"